version: '3.3'

services:
  mysql:
    image: mysql_local:0.0.2
    container_name: "mysqldb"
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ="Asia/Seoul"
